% ANNOTATEMASK Adds cell annotation (label) column to data matrix 
% 
%   [B,missed,duplicates] = annotatemask(mask,imID,tablename,P)
%
% INPUT 
%   mask       Binary mask of objects from image with id: imID
%   imID       Cell of string carrying image id. 
%   tablename  Filename string of table (e.g. 'HE_table.txt')
%   P          Posterior maps (~ x ~ x k matrix) 
%
% OUTPUT
%   B          Objects data matrix with string cell label appended as last column. 
%   missed     Number of markers falling on backgorund
%   duplicates Number of times multiple markers fall on the same object
%
% DESCRIPTION
% Appends a string label column to the end of the data matrix B. B is
% generated by improps() over the mask, in addition to mean/max/min of 
% each of R,G,&B intensity values as features, and neighborhood sampling
% class proportions. The labels correspond to cell type (cancer, lymphocyte, 
% macrophage, stromal, vascular enothelial,...). The first column in B is imID.   

% Jimmy Azar, jimmy.azar@gmail.com
% annotatemask.m, 2016/07/12


function [B,missed,duplicates] = annotatemask(mask,imID,tablename,P)

if nargin < 4 | isempty(P)
	warning('No posterior maps specified!');
    return;
end

if nargin < 3 | isempty(tablename)
	warning('No table for cell markers specified!');
    return;
end

if nargin < 2 | isempty(imID)
	warning('No image ID specified!');
    return;
end

if nargin < 1 | isempty(mask)
	warning('No binary mask specified!');
    return;
end


table = readcsvcell(tablename);
d = table.data;
f = strcmp(d(:,2),imID);
f2 = (strcmp(d(:,1),'Cancer') | strcmp(d(:,1),'Lymphocyte') | ...
      strcmp(d(:,1),'Stromal') | strcmp(d(:,1),'VascularEndothel') | ...
      strcmp(d(:,1),'Macrophage'));
f = (f & f2); 

xy = str2double(d(f,[4 5]));
labels = d(f,1);
L = bwlabel(mask);
B = improps(mask);

%add mean r,b,g values of objects
I = imread(char(imID));
I = double(I);
tr = I(:,:,1);
tg = I(:,:,2);
tb = I(:,:,3);
Ir = regionprops(mask,tr,'MeanIntensity','MinIntensity','MaxIntensity');
Ig = regionprops(mask,tg,'MeanIntensity','MinIntensity','MaxIntensity');
Ib = regionprops(mask,tb,'MeanIntensity','MinIntensity','MaxIntensity');
B = [B cat(1,Ir.MeanIntensity) cat(1,Ir.MinIntensity) cat(1,Ir.MaxIntensity) ...
       cat(1,Ig.MeanIntensity) cat(1,Ig.MinIntensity) cat(1,Ig.MaxIntensity) ...
       cat(1,Ib.MeanIntensity) cat(1,Ib.MinIntensity) cat(1,Ib.MaxIntensity)];

%Add neighborhood sampling info around each object in mask
%[Y] = circsample(mask,P,1,33); % consider only 1 large neighborhood annulus
%B = [B Y];

ind = sub2ind(size(L),xy(:,2),xy(:,1));
objID = L(ind);

%Prepare to remove labels of repeting objID's by setting to zero
u = sort(unique(objID),'ascend');
N = histc(objID,u);
v = u(N>1);
missed = sum(objID==0);
duplicates = sum(N(N>1 & (u~=0)));
for i=1:length(v)
    objID(objID==v(i))=0;
end   
%Remove labels of clicks not in objects
labels(objID==0) = []; 
objID(objID==0) = [];

B = num2cell(B);
B(objID,end+1) = labels; %repetitions in objID are possible
B = [repmat(imID,size(B,1),1) B];

end

