% MASK2FEAT Extracts features from mask objects  
% 
%   [B] = mask2feat(mask,P)
%
% INPUT 
%   mask       Binary mask of objects 
%   P          Posterior maps (~ x ~ x k matrix) 
%   I          Original RGB image
%
% OUTPUT
%   B          Objects data matrix, unlabeled 
%
% DESCRIPTION
% B is generated by improps() over the mask, in addition to mean/max/min of 
% each of R, G, & B intensity values as features, and neighborhood sampling
% class proportions.

% Jimmy Azar, jimmy.azar@gmail.com
% mask2feat.m, 2016/08/03


function [B] = mask2feat(mask,P,I)

if nargin < 3 | isempty(I)
	warning('Original image not specified!');
    return;
end

if nargin < 2 | isempty(P)
	warning('No posterior maps specified!');
    return;
end

if nargin < 1 | isempty(mask)
	warning('No binary mask specified!');
    return;
end

L = bwlabel(mask);
B = improps(mask); %extract 'Area','Solidity','Eccentricity','EquivDiameter','Extent','MajorAxisLength','MinorAxisLength','Perimeter'

%add mean r,b,g values of objects
I = double(I);
tr = I(:,:,1);
tg = I(:,:,2);
tb = I(:,:,3);
Ir = regionprops(mask,tr,'MeanIntensity','MinIntensity','MaxIntensity');
Ig = regionprops(mask,tg,'MeanIntensity','MinIntensity','MaxIntensity');
Ib = regionprops(mask,tb,'MeanIntensity','MinIntensity','MaxIntensity');
B = [B cat(1,Ir.MeanIntensity) cat(1,Ir.MinIntensity) cat(1,Ir.MaxIntensity) ...
       cat(1,Ig.MeanIntensity) cat(1,Ig.MinIntensity) cat(1,Ig.MaxIntensity) ...
       cat(1,Ib.MeanIntensity) cat(1,Ib.MinIntensity) cat(1,Ib.MaxIntensity)];

%add neighborhood sampling info around each object in mask
%[Y] = circsample(mask,P,1,33); % consider only 1 large neighborhood annulus
%B = [B Y];

%%B = num2cell(B);
%%B = [repmat(imID,size(B,1),1) B];
end